---

expid: 2
runs: 1
log_level: INFO
base_path: data/NYC
dataset_name: NYC.npz

model_name: TGCSRN
seed: 1234
test_only: True
device: cuda:1
data:

  freq: 30min

  cluster_num: 90
  poi_cluster: 4
  train_batch_size: 64
  test_batch_size: 64
  val_batch_size: 64

  num_for_predict: 6
  num_for_target: 1

model:
  input_dim: 2
  hidden_dim: 64
  output_dim: 2
  gcn_depth: 2
  norm_graph: sym
  dropout_prob: 0.2
  activation_type: relu
  fuse_type : average
  node_emb : 10

train:
  base_lr: 0.001
  weight_decay: 0.0001
  milestones: [50, 90, 130, 170]
  lr_decay_ratio: 0.5
  min_learning_rate: 2.0e-06

  max_grad_norm: 5

  load_initial: False
  test_only: False
  tolerance: 50

  epoch_start: 0
  epochs: 200
  global_step: 0
  print_every: 1

  description:
  best_mode: Result/TGCSRN/30min/ckpt/NYC.pth



